# Generated by Django 5.1.2 on 2024-11-24 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The store branch's name", max_length=70)),
                ('address_1', models.CharField(help_text='Address field 1', max_length=100)),
                ('address_2', models.CharField(help_text='Address field 2', max_length=100)),
                ('contact_number', models.CharField(help_text="The store branch's contact number", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DOOR', 'Door'), ('TILE', 'Tile'), ('WINDOW', 'Window')], max_length=20, verbose_name='Product Type')),
                ('price', models.DecimalField(decimal_places=2, help_text='The price of the Product when sold on the Store', max_digits=6)),
                ('cost', models.DecimalField(decimal_places=2, help_text='The price of the Product when bought from the Supplier', max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='BranchProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.product')),
            ],
        ),
    ]
