# Generated by Django 5.1.2 on 2024-11-26 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The Window's Name", max_length=20)),
                ('description', models.TextField(help_text="The Window's Description")),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stores.product')),
            ],
        ),
    ]
