# Generated by Django 5.1.2 on 2024-11-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='default', help_text="The Product's Description"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='default', help_text="The Product's Name", max_length=20),
            preserve_default=False,
        ),
    ]
