# Generated by Django 5.1.2 on 2025-02-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_product_description_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='door_thumbnail.jpg', upload_to='product_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, help_text='The value of the Product when bought from the Supplier', max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='The value of the Product when sold on the Store', max_digits=6),
        ),
    ]
